# Servidor y Puerto
server.port=8083
server.address=0.0.0.0
storage.location=/mnt/7yrak/TYRAK-BOX/data-tyrak-box
sync.enabled=true
sync.source-location=/mnt/7yrak/TYRAK-BOX/tyrakSync
sync.username=sergio
logging.level.org.hibernate.SQL=DEBUG

# Conexión Directa a la Base de Datos tyrak_box
spring.datasource.url=jdbc:postgresql://10.51.9.17:5432/tyrak_box
spring.datasource.username=sergiofica
spring.datasource.password=local1234$
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del Cuidado del Mapeo JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Límites de Subida de Archivos Ilimitados (o extremadamente grandes)
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

# Ajustes extras para que Tomcat no aborte subidas largas
server.tomcat.max-swallow-size=-1
server.tomcat.connection-timeout=600000
spring.mvc.async.request-timeout=600000
